/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Selection: THREE.Mesh
    Selection_1: THREE.Mesh
    Selection_2: THREE.Mesh
  }
  materials: {
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null!)
  const { nodes, materials } = useGLTF('/books.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="books" position={[3.16, 1.28, -1.53]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh name="Selection" geometry={nodes.Selection.geometry} material={materials['Material.020']} />
        <mesh name="Selection_1" geometry={nodes.Selection_1.geometry} material={materials['Material.024']} />
        <mesh name="Selection_2" geometry={nodes.Selection_2.geometry} material={materials['Material.026']} />
      </group>
    </group>
  )
}

useGLTF.preload('/books.glb')
