/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useLoader } from "@react-three/fiber";
import { TextureLoader } from "three";
import Candle from "./Candle";
import Books from "./Books";
import Window from "./Window";
import MyFire from "../shaders/MyFire";
import Encyclopedia from "./Encyclopedia";

type GLTFResult = GLTF & {
  nodes: {
    Circle: THREE.Mesh;
    NurbsPath: THREE.Mesh;
    sofa: THREE.Mesh;
    Painting: THREE.Mesh;
    CenterTable: THREE.Mesh;
    Lamp: THREE.Mesh;
    Carpet: THREE.Mesh;
    curtains: THREE.Mesh;
    CenterTablePlant: THREE.Mesh;
    plant: THREE.Mesh;
    ["wall-lamps"]: THREE.Mesh;
    Lg_Curved_Oled_Tv: THREE.Mesh;
    display_wall: THREE.Mesh;
    flower_vase_2: THREE.Mesh;
    nataraj: THREE.Mesh;
    decor1: THREE.Mesh;
    flower_vase: THREE.Mesh;
    decor5: THREE.Mesh;
    sphere: THREE.Mesh;
    wooden_elephant: THREE.Mesh;
    decor2: THREE.Mesh;
    picture_frame: THREE.Mesh;
    marble_bust: THREE.Mesh;
    Radha_Krishna: THREE.Mesh;
    Crocodile_Decor: THREE.Mesh;
    decor3: THREE.Mesh;
    horse: THREE.Mesh;
    ["hour-glass"]: THREE.Mesh;
    swan: THREE.Mesh;
    ["fire-place"]: THREE.Mesh;
    skeleton: THREE.Mesh;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/scene1.glb") as GLTFResult;
  const [
    skeleton,
    displayWall,
    painting,
    carpet,
    sofa,
    curtain,
    plant,
    table,
    tablePlant,
    lamp,
    pendent,
    tv,
    wallLight,
    decor2,
    croco,
    decor5,
    horse,
    hourGlass,
    flowerVase,
    decor1,
    radheKrishna,
    swan,
    nataraja,
    flowerVase2,
    decor3,
    elephant,
    photoFrame,
    statue,
    sphere,
    fireplace,
  ] = useLoader(TextureLoader, [
    "/textures/skeleton.jpg",
    "/textures/display.jpg",
    "/textures/painting.jpg",
    "/textures/carpet.jpg",
    "/textures/sofaD.jpg",
    "/textures/curtain.png",
    "/textures/plant.jpg",
    "/textures/table.jpg",
    "/textures/tableplant.jpg",
    "/textures/lamp.jpg",
    "/textures/pendent.jpg",
    "/textures/tv.jpg",
    "/textures/walllight.jpg",
    "/textures/decor2.jpg",
    "/textures/croco.jpg",
    "/textures/decor5.jpg",
    "/textures/horse.jpg",
    "/textures/hourGlass.png",
    "/textures/flowerVase.jpg",
    "/textures/decor1.jpg",
    "/textures/radheKrishna.jpg",
    "/textures/swan.jpg",
    "/textures/nataraja.jpg",
    "/textures/flowerVase2.jpg",
    "/textures/decor3.jpg",
    "/textures/elephant.jpg",
    "/textures/photoFrame.jpg",
    "/textures/statue.jpg",
    "/textures/sphere.jpg",
    "/textures/fireplace.jpg",
  ]);

  skeleton.flipY = false;
  displayWall.flipY = false;
  painting.flipY = false;
  carpet.flipY = false;
  sofa.flipY = false;
  curtain.flipY = false;
  plant.flipY = false;
  table.flipY = false;
  tablePlant.flipY = false;
  lamp.flipY = false;
  pendent.flipY = false;
  tv.flipY = false;
  wallLight.flipY = false;
  decor2.flipY = false;
  croco.flipY = false;
  decor5.flipY = false;
  horse.flipY = false;
  hourGlass.flipY = false;
  flowerVase.flipY = false;
  decor1.flipY = false;
  radheKrishna.flipY = false;
  swan.flipY = false;
  nataraja.flipY = false;
  flowerVase2.flipY = false;
  decor3.flipY = false;
  elephant.flipY = false;
  photoFrame.flipY = false;
  statue.flipY = false;
  sphere.flipY = false;
  fireplace.flipY = false;

  return (
    <group {...props} dispose={null}>
      <Candle position={[3.1, 2.585, 1.9]} />
      <Candle position={[3.1, 0.44, -1.85]} />
      <Books />
      <Encyclopedia />
      <Window />
      <MyFire
        color
        position={[3.07, 0.75, -0.06]}
        scale={1}
        rotation={[Math.PI, -1.57, Math.PI]}
      />

      <group
        name="Pendant-Modern-Lighting"
        position={[-0.42, 2.93, -0.57]}
        rotation={[0, 0, Math.PI]}
      >
        <mesh
          name="Circle"
          geometry={nodes.Circle.geometry}
          position={[0, -0.4, 0]}
        >
          <meshBasicMaterial
            attach="material"
            map={pendent}
            side={THREE.DoubleSide}
          />
        </mesh>
        <mesh
          name="NurbsPath"
          geometry={nodes.NurbsPath.geometry}
          scale={[0.15, 0.1, 0.15]}
        />
      </group>
      <mesh
        name="sofa"
        geometry={nodes.sofa.geometry}
        position={[-1.56, 0.51, -1.53]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial
          attach="material"
          map={sofa}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="Painting"
        geometry={nodes.Painting.geometry}
        position={[-3.54, 1.91, -0.71]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <meshBasicMaterial
          attach="material"
          map={painting}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="CenterTable"
        geometry={nodes.CenterTable.geometry}
        position={[-0.25, 0.23, -0.3]}
      >
        <meshBasicMaterial
          attach="material"
          map={table}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="Lamp"
        geometry={nodes.Lamp.geometry}
        position={[-3.03, 0.04, 2.34]}
        rotation={[Math.PI, -1.01, Math.PI]}
      >
        <meshBasicMaterial
          attach="material"
          map={lamp}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="Carpet"
        geometry={nodes.Carpet.geometry}
        position={[-0.97, 0.06, -0.2]}
      >
        <meshBasicMaterial
          attach="material"
          map={carpet}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="curtains"
        geometry={nodes.curtains.geometry}
        position={[0, 0.02, 5.4]}
      >
        <meshBasicMaterial
          attach="material"
          map={curtain}
          side={THREE.DoubleSide}
          transparent={true}
        />
      </mesh>
      <mesh
        name="CenterTablePlant"
        geometry={nodes.CenterTablePlant.geometry}
        position={[-0.25, 0.23, -0.3]}
      >
        <meshBasicMaterial
          attach="material"
          map={tablePlant}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="plant"
        geometry={nodes.plant.geometry}
        position={[1.79, 0.05, -6.19]}
      >
        <meshBasicMaterial
          attach="material"
          map={plant}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="wall-lamps"
        geometry={nodes["wall-lamps"].geometry}
        position={[2.84, 2.15, -0.01]}
      >
        <meshBasicMaterial
          attach="material"
          map={wallLight}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="Lg_Curved_Oled_Tv"
        geometry={nodes.Lg_Curved_Oled_Tv.geometry}
        position={[3.11, 1.67, -0.04]}
        rotation={[0, -Math.PI / 2, 0]}
      >
        <meshBasicMaterial attach="material" map={tv} side={THREE.DoubleSide} />
      </mesh>
      <mesh
        name="display_wall"
        geometry={nodes.display_wall.geometry}
        position={[3.02, 1.5, 1.66]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      >
        <meshBasicMaterial
          attach="material"
          map={displayWall}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="flower_vase_2"
        geometry={nodes.flower_vase_2.geometry}
        position={[3.08, 0.81, 1.48]}
      >
        <meshBasicMaterial
          attach="material"
          map={flowerVase2}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="nataraj"
        geometry={nodes.nataraj.geometry}
        position={[3.03, 1.15, 1.48]}
      >
        <meshBasicMaterial
          attach="material"
          map={nataraja}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="decor1"
        geometry={nodes.decor1.geometry}
        position={[3.16, 0.92, -1.85]}
      >
        <meshBasicMaterial
          attach="material"
          map={decor1}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="flower_vase"
        geometry={nodes.flower_vase.geometry}
        position={[3.11, 2.62, -1.89]}
      >
        <meshBasicMaterial
          attach="material"
          map={flowerVase}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="decor5"
        geometry={nodes.decor5.geometry}
        position={[3.2, 2.6, -1.46]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <meshBasicMaterial
          attach="material"
          map={decor5}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="sphere"
        geometry={nodes.sphere.geometry}
        position={[3.12, 2.59, 1.85]}
      >
        <meshBasicMaterial
          attach="material"
          map={sphere}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="wooden_elephant"
        geometry={nodes.wooden_elephant.geometry}
        position={[3.11, 1.88, 1.94]}
      >
        <meshBasicMaterial
          attach="material"
          map={elephant}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="decor2"
        geometry={nodes.decor2.geometry}
        position={[3.1, 1.59, -1.4]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      >
        <meshBasicMaterial
          attach="material"
          map={decor2}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="picture_frame"
        geometry={nodes.picture_frame.geometry}
        position={[3.05, 1.88, 1.47]}
        rotation={[0, -1.57, 0]}
      >
        <meshBasicMaterial
          attach="material"
          map={photoFrame}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="marble_bust"
        geometry={nodes.marble_bust.geometry}
        position={[3.1, 2.59, 1.44]}
        rotation={[0, -1.55, 0]}
      >
        <meshBasicMaterial
          attach="material"
          map={statue}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="Radha_Krishna"
        geometry={nodes.Radha_Krishna.geometry}
        position={[3.12, 1.39, -1.96]}
      >
        <meshBasicMaterial
          attach="material"
          map={radheKrishna}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="Crocodile_Decor"
        geometry={nodes.Crocodile_Decor.geometry}
        position={[3.18, 0.13, -1.67]}
        rotation={[Math.PI / 2, 0, 1.23]}
      >
        <meshBasicMaterial
          attach="material"
          map={croco}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="decor3"
        geometry={nodes.decor3.geometry}
        position={[3.06, 1.6, 1.95]}
        rotation={[1.57, 0, 1.51]}
      >
        <meshBasicMaterial
          attach="material"
          map={decor3}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="horse"
        geometry={nodes.horse.geometry}
        position={[3.2, 2.59, -1.46]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <meshBasicMaterial
          attach="material"
          map={horse}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="hour-glass"
        geometry={nodes["hour-glass"].geometry}
        position={[3.2, 2.59, -1.46]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <meshBasicMaterial
          attach="material"
          map={hourGlass}
          transparent={true}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="swan"
        geometry={nodes.swan.geometry}
        position={[3.06, 1.6, 1.95]}
        rotation={[1.57, 0, 1.51]}
      >
        <meshBasicMaterial
          attach="material"
          map={swan}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="fire-place"
        geometry={nodes["fire-place"].geometry}
        position={[3.11, 0.83, -0.06]}
        rotation={[Math.PI, -1.57, Math.PI]}
      >
        <meshBasicMaterial
          attach="material"
          map={fireplace}
          side={THREE.DoubleSide}
        />
      </mesh>
      <mesh
        name="skeleton"
        geometry={nodes.skeleton.geometry}
        position={[-0.29, 1.54, 5.4]}
      >
        <meshBasicMaterial
          attach="material"
          map={skeleton}
          side={THREE.DoubleSide}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/scene1.glb");
